# version: '3'
services:
  nuxt-quasar-web:
    #restart: always
    restart: on-failure:3
    container_name: nuxt-quasar-web
    build: .
    # image: "nuxt-quasar-web:latest"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
