# version: '3'
services:
  gd5-webapp:
    #restart: always
    restart: on-failure:3
    container_name: nuxt3-quasar-webapp
    # build: .
    image: "nuxt3-quasar-webapp:latest"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
